(require 'leanote)
(describe "test leanote-notebook-has-note-p"
          :var (notes)
          (it "test"
              (setq notes '[((PublicTime . "0001-01-01T00:00:00Z")
                             (UpdatedTime . "2016-07-23T20:57:20.651474234+08:00")
                             (CreatedTime . "0001-01-01T00:00:00Z")
                             (Files)
                             (Usn . 151)
                             (IsDeleted . :json-false)
                             (IsTrash . :json-false)
                             (IsBlog . :json-false)
                             (IsMarkdown . t)
                             (Content . "")
                             (Abstract . "# abc\n这是测试文件\n\n## 二级目录\n1. a\n2. b\n3. c\n\n### 第三级目录\n第三级内容\n\n## 另一个二级目录\n* a\n* bb\n* cc\n* dd\n")
                             (Tags)
                             (Desc . "")
                             (Title . "abc")
                             (UserId . "5781be6dab644133ed006e61")
                             (NotebookId . "57899e70c3b1f40b51000007")
                             (NoteId . "5793514eab644133ed01f5be"))])
              (expect (leanote-notebook-has-note-p notes "abc")
                      :to-be t)
              (expect (leanote-notebook-has-note-p notes "ddd")
                      :to-be nil)))
